url: "https://vonhirschfeld.eu/niklas"
baseurl: "https://vonhirschfeld.eu/niklas"
safe: true
markdown: kramdown
kramdown:
    parse_block_html: true
excerpt_seperator: ""
permalink: pretty
include: [_data]
